---
- name: Larnin Loops
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Debug through a loop
    debug:
      msg: "We want this to print out next {{ item.0 }}  poodles {{ item.1}}"
             #    with_items
    loop:
    - [dog are kinda cool, but they drool]
    - cat
    - hamster
