--- 
- name: Using debug with ansible_vars
  hosts: nam

  vars:
    Napya: cool class

  vars_prompt:
  - name: "mypass"
    prompt: "What is your password"
  
  tasks:
  - name: Print out ansible_os_family
    debug:
      msg: "This machine is in the {{ ansible_os_family }} family"
      
  - name: Print out the ansible_pkg_mgr
    debug:
      var: ansible_pkg_mgr

  - name: Get Nam's Personal Information
    shell: ls /home/student/mycode/
    register: goodies

  - name: Print out the goodies
    debug:
      var: goodies
